= Tp1

image: https: //img.shields.io/badge/vert.x-3.8.3-purple.svg [link = "https://vertx.io"]

TP Cara Vertx

Context:
To simulate the arrival of Customers, Restaurant Vericle sends Json messages to the Server containing a customer and its status.
At this stage, the sent messages are lost, you can see it by launching the application:
`` ''
Failed to send to: restaurant.serveur
Failed to send to: restaurant.serveur
Failed to send to: restaurant.serveur
`` ''

== Question 1.RestaurantLauncher
Modify the code to start several occurrences of Servers Verticles and Cook verticles using the variables serversNb and cooksNb

== Question 2.VerticleServer
Instantiate eventBus to receive messages sent by RestaurantVerticle

== Question 3.VerticleServer
Set up the reception of messages sent by the Restaurant (typed Customer sent in Json format)

== Question 4.VerticleServer
At the reception of a customer, count it in a Counter counter in a space vertx.sharedData ()

== Question 5.VerticleServer
Same as question 4 but this time store the client object in a Map (LocalMap or AsynchronousMap)
When welcoming a customer, store the customer in a vertx.sharedData () space typed Map

= Tp2

image: https: //img.shields.io/badge/vert.x-3.8.3-purple.svg [link = "https://vertx.io"]

Context:

We will try to implement an HTTP server so that we can display the results we receive on the console in a web page.

== Question 1.RestaurantVerticle

Implement an Http server in the RestaurantVerticle class.
Implement a vertx router.

== Question 2

Implement a handler to pass paramateres on a specified url
Pass the answer towards the road.

= Tp3

image: https: //img.shields.io/badge/vert.x-3.8.3-purple.svg [link = "https://vertx.io"]

TP Cara Vertx

Context:

The preparation of dishes in the kitchen takes more or less long.
this time spent blocks the eventloop and penalizes the overall application.

== Question 1.RestaurantLauncher
Implement a worker_verticle


== Question 2.
Launch the jar in high availability mode
-mvn clean install


== Help
* https://blog.invivoo.com/vert-x-basics-concurrence-et-scalabilite-avec-les-verticles/[Vert.x Verticles]
* https://www.mednikov.net/vertx-eventbus/[Vert.x EventBus]
* https://vertx.io/docs/vertx-core/java/#_asynchronous_counters[Counter]
* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]
